# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: sktr22@github.com
author_full_name: sktr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-time-skill-py
github_username: stkr22
project_description: 'Time Management Skill for the Private Assistant: Handles timers,
    time telling, and other time-related functionalities.'
project_name: Private Assistant Time Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-time-skill
python_package_import_name: private_assistant_time_skill
python_package_version: 1.2.1
use_containers: true
