FROM mcr.microsoft.com/devcontainers/base@sha256:5bdd3844bb205db079749b9c09f61e454ca9764fd867a294500b505147336fd8
COPY --from=ghcr.io/astral-sh/uv:0.5.9 /uv /uvx /bin/
ENV VIRTUAL_ENV=/workspaces/.venv
ENV UV_PROJECT_ENVIRONMENT=/workspaces/.venv
RUN mkdir -p /workspaces && \
    chown -R vscode:vscode /workspaces
USER vscode
